# Generated by Django 4.1.7 on 2023-05-02 05:19

from django.db import migrations, models

def populate_category(apps, schema_editor):
    categories_names = [
        'Technology',
        'Travel',
        'Fashion',
        'Health and Fitness',
        'Food and Cooking',
        'Business and Finance',
        'Lifestyle',
        'Entertainment',
        'Sports',
        'News',
        'Politics'
        'Science',
        'AI',
        'Management',
        'Opinions',
        'Potery',
    ]
      
    Category = apps.get_model('blog', 'Category')
    for category_name in categories_names:
        Category.objects.create(title=category_name)
    
class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_categories'),
    ]

    operations = [
        migrations.RunPython(populate_category)
    ]
